services:
  app:
    image: myapp:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - APP_PORT=${APP_PORT:-3000}
      - APP_HOST=${APP_HOST:-0.0.0.0}
    command: air
    volumes:
      - ./public:/app/public
      - ./views:/app/views
      - ./internal:/app/internal
      - ./cmd:/app/cmd
      - ./.air.toml:/app/.air.toml
